/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kopanitsa_common_camera_CameraUtil */

#ifndef _Included_com_kopanitsa_common_camera_CameraUtil
#define _Included_com_kopanitsa_common_camera_CameraUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kopanitsa_common_camera_CameraUtil
 * Method:    decodeYUV_native
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_com_kopanitsa_common_camera_CameraUtil_decodeYUV_1native
  (JNIEnv *, jclass, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
